Repository wecode-bootcamp-korea/19-2nd-Wa-Grano-frontend, pull requests merged in 2021-05, with the labels that each got.

#4 [19기 홍진아] nav바 레이아웃 구현
  public/images/logo.jpg
  src/Component/Nav/Nav.js
  src/Component/Nav/Nav.scss
  src/Routes.js
Labels: Status: Accepted

#3 [19기 강서형]main layout 구성중
  public/MainImg/busanMain1.jpg
  public/MainImg/busanvilage.jpg
  public/MainImg/kamchun.jpg
  public/MainImg/ocean.jpg
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/mainData.js
  src/index.js
Labels: Status: 리뷰 요청

#7 [19기 강서형] "Main Filter layout 완료 및 기능구현중"
  src/Pages/Main/Filter/Filter.js
  src/Pages/Main/Filter/Filter.scss
  src/Pages/Main/Filter/FilterData.js
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: 리뷰 요청

#8 [19기 강서형] mainSlide layout 완료
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#2 [19기 김태현] 리스트 페이지 초기화 기능 완료
  public/data/photos/limit=9&offset=1.json
  public/data/photos/limit=9&offset=2.json
  public/data/photos/limit=9&offset=3.json
  public/data/photos/limit=9&offset=4.json
  public/data/photos/limit=9&offset=5.json
  public/data/photos/limit=9&offset=6.json
  public/data/productActivityData.json
  public/data/productListData1.json
  public/data/productListData2.json
  public/data/productListData3.json
  src/Pages/Main/Main.js
  src/Pages/ProductList/Components/Activity/Activity.js
  src/Pages/ProductList/Components/Activity/ActivityMain/ActivityMain.js
  src/Pages/ProductList/Components/Activity/ActivityMain/ActivityMainList/ActivityMainList.js
  src/Pages/ProductList/Components/Activity/ActivityTap/ActivityTap.js
  src/Pages/ProductList/Components/Activity/ActivityTap/CategoriList/CategoriList.js
  src/Pages/ProductList/Components/Banner/Banner.js
  src/Pages/ProductList/Components/CardList/Card/Card.js
  src/Pages/ProductList/Components/CardList/CardList.js
  src/Pages/ProductList/Components/Header/Header.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Routes.js
Labels: Status: 추가 기능 구현중

#9 [19기 강서형 ]mainSlide layout 완료
  public/data/MainSlideData.json
  src/Pages/Main/Main.js
  src/Pages/Main/MainSlide/MainSlide.js
  src/Pages/Main/MainSlide/MainSlide.scss
  src/Pages/Main/mainData.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#6 [19기 홍진아] login, signUp 완료
  public/images/facebook.jpg
  public/images/google.jpg
  public/images/kakao.jpg
  public/images/naver.jpg
  src/Component/Nav/Nav.js
  src/Component/Nav/Nav.scss
  src/Pages/Login/Components/Button.js
  src/Pages/Login/Components/Button.scss
  src/Pages/Login/Components/Form.js
  src/Pages/Login/Components/Form.scss
  src/Pages/Login/Components/Input.js
  src/Pages/Login/Components/Input.scss
  src/Pages/Login/Components/Social.js
  src/Pages/Login/Components/Social.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/SignUp/Components/AllBox.js
  src/Pages/SignUp/Components/AllBox.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/config.js
Labels: Status: Accepted

#5 [19기 박세리] add : layout complete
  bash.exe.stackdump
  package-lock.json
  src/Pages/Main/Main.js
  src/Pages/ProductDetail/Components/Description/Description.js
  src/Pages/ProductDetail/Components/Description/Description.scss
  src/Pages/ProductDetail/Components/IncludedOptions/IncludedOptions.js
  src/Pages/ProductDetail/Components/IncludedOptions/IncludedOptions.scss
  src/Pages/ProductDetail/Components/Map/Map.js
  src/Pages/ProductDetail/Components/Map/Map.scss
  src/Pages/ProductDetail/Components/OptionDetails/OptionDetails.js
  src/Pages/ProductDetail/Components/OptionDetails/OptionDetails.scss
  src/Pages/ProductDetail/Components/Photos/Photos.js
  src/Pages/ProductDetail/Components/Photos/Photos.scss
  src/Pages/ProductDetail/Components/Regulations/Regulations.js
  src/Pages/ProductDetail/Components/Regulations/Regulations.scss
  src/Pages/ProductDetail/Components/Title/Title.js
  src/Pages/ProductDetail/Components/Title/Title.scss
  src/Pages/ProductDetail/Img/buffet.jpg
  src/Pages/ProductDetail/Img/newmap.jpg
  src/Pages/ProductDetail/Img/newmaptitle.jpg
  src/Pages/ProductDetail/Img/nightview.jpg
  src/Pages/ProductDetail/ProductDetail.js
Labels: Status: 수정 요청
